---
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - caddy
      - dnsmasq
      - syslinux-nonlinux
      - shim-x64
    state: present

- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ tftp_root }}"
    - "{{ tftp_root }}/pxelinux.cfg"
    - "{{ http_root }}"
    - "{{ http_root }}/fedora_server"

- name: Configure dnsmasq
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "/etc/dnsmasq.conf"
    mode: "0644"
  notify:
    - Restart dnsmasq

- name: Enable dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: true

- name: Download iPXE (BIOS)
  ansible.builtin.get_url:
    url: "http://boot.ipxe.org/undionly.kpxe"
    dest: "{{ tftp_root }}/undionly.kpxe"
    checksum: "sha256:d7cfb8bdcbfdcf86fd7210a4677121ec3535495cf0985a51fea63200aebbd2cd"

- name: Download iPXE (UEFI)
  ansible.builtin.get_url:
    url: "https://boot.ipxe.org/x86_64-efi/ipxe.efi"
    dest: "{{ tftp_root }}/ipxe.efi"
    checksum: "sha256:93999fb8a5fc9f558c2e3c13773f104ad85c933f4cf14f81604c0ee344779866"

- name: Create iPXE autoexec
  ansible.builtin.template:
    src: autoexec.ipxe.j2
    dest: "{{ tftp_root }}/autoexec.ipxe"
    mode: "0644"

- name: Download Fedora ISO
  ansible.builtin.get_url:
    url: "{{ iso_url }}"
    checksum: "sha256:{{ iso_sha256 }}"
    dest: "{{ http_root }}/fedora_server/fedora.iso"

- name: Mount Fedora ISO under HTTP root
  ansible.builtin.mount:
    src: "{{ http_root }}/fedora_server/fedora.iso"
    path: "{{ http_root }}/fedora_server/iso"
    fstype: iso9660
    opts: loop,ro
    state: mounted

- name: Create Fedora kickstart file (if provided)
  ansible.builtin.copy:
    src: "{{ kickstart_src }}"
    dest: "{{ http_root }}/fedora_server/ks.cfg"
    mode: "0644"
  when: kickstart_src | length > 0

- name: Set SELinux boolean for Caddy to be able to read HTTP content
  ansible.posix.seboolean:
    name: httpd_read_user_content
    state: true
    persistent: true

- name: Ensure correct SELinux context on TFTP root
  ansible.builtin.command: restorecon -Rv {{ tftp_root }}
  changed_when: false

- name: Ensure correct SELinux context on HTTP root
  ansible.builtin.command: restorecon -Rv {{ http_root }}
  changed_when: false

- name: Configure Caddy
  ansible.builtin.template:
    src: "Caddyfile.j2"
    dest: "/etc/caddy/Caddyfile"
    mode: "0644"
  notify:
    - Restart Caddy

- name: Enable Caddy
  ansible.builtin.systemd:
    name: caddy
    enabled: true

- name: Allow traffic through firewall
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - dhcp
    - http
    - proxy-dhcp
    - tftp